# theme: jekyll-theme-cayman
# remote_theme: pmarsceill/just-the-docs
remote_theme: bcole/just-the-docs

title: Intuit API Docs
description: Documentation for Intuit's APIs

permalink: pretty

gh_edit_link: true
